/*
 * global.h
 *
 *  Created on: 16 Sep 2019
 *      Author: droggen
 */

#ifndef GLOBAL_H_
#define GLOBAL_H_

#include <stdio.h>
#include "command.h"


extern FILE *file_usb,*file_pri,*file_bt,*file_itm,*file_dbg;
extern unsigned char system_devname[];
extern unsigned char sharedbuffer[];
extern unsigned char system_mode;

extern unsigned char __mode_sleep;

#define CONFIG_ADDR_ENABLE_ID 0
#define CONFIG_ADDR_ENABLE_TIMESTAMP 1
#define CONFIG_ADDR_ENABLE_BATTERY 2
#define CONFIG_ADDR_ENABLE_ACCELERATION 3
#define CONFIG_ADDR_ENABLE_GYROSCOPE 4
#define CONFIG_ADDR_ENABLE_CHECKSUM 5
#define CONFIG_ADDR_DATA_FORMAT 6
//#define CONFIG_ADDR_SENSORSR 10
#define CONFIG_ADDR_STREAM_FORMAT 11
#define CONFIG_ADDR_ENABLE_TEMPERATURE 12
#define CONFIG_ADDR_STREAM_BINARY 13
//#define CONFIG_ADDR_ADC_MASK 14
//#define CONFIG_ADDR_ADC_PERIOD0 15
//#define CONFIG_ADDR_ADC_PERIOD1 16
//#define CONFIG_ADDR_ADC_PERIOD2 17
//#define CONFIG_ADDR_ADC_PERIOD3 18
#define CONFIG_ADDR_ENABLE_LCD 19
#define CONFIG_ADDR_TS_PERIOD0 20
#define CONFIG_ADDR_TS_PERIOD1 21
#define CONFIG_ADDR_TS_PERIOD2 22
#define CONFIG_ADDR_TS_PERIOD3 23
#define CONFIG_ADDR_STREAM_LABEL 24
#define CONFIG_ADDR_STREAM_PKTCTR 25
#define CONFIG_ADDR_ENABLE_INFO 26



// Boot script - reserve 100 bytes
#define CONFIG_ADDR_SCRIPTSTART 100
#define CONFIG_ADDR_SCRIPTLEN COMMANDMAXSIZE
#define CONFIG_ADDR_SCRIPTEND (CONFIG_ADDR_SCRIPTSTART+CONFIG_ADDR_SCRIPTLEN-1)

// Storing number of boots
#define STATUS_ADDR_NUMBOOT0	300
#define STATUS_ADDR_NUMBOOT1	301
#define STATUS_ADDR_NUMBOOT2	302
#define STATUS_ADDR_NUMBOOT3	303

// Storing charge status upon soft off
#define STATUS_ADDR_OFFCURRENT_VALID 500
#define STATUS_ADDR_OFFCURRENT_CHARGE0 501
#define STATUS_ADDR_OFFCURRENT_CHARGE1 502
#define STATUS_ADDR_OFFCURRENT_CHARGE2 503
#define STATUS_ADDR_OFFCURRENT_CHARGE3 504
#define STATUS_ADDR_OFFCURRENT_VOLTAGE0 505
#define STATUS_ADDR_OFFCURRENT_VOLTAGE1 506
#define STATUS_ADDR_OFFCURRENT_H 510
#define STATUS_ADDR_OFFCURRENT_M 511
#define STATUS_ADDR_OFFCURRENT_S 512
#define STATUS_ADDR_OFFCURRENT_DAY 513
#define STATUS_ADDR_OFFCURRENT_MONTH 514
#define STATUS_ADDR_OFFCURRENT_YEAR 515
#define STATUS_ADDR_OFFCURRENT_TIME 516
#define STATUS_ADDR_OFFCURRENT_TIME_1 517
#define STATUS_ADDR_OFFCURRENT_TIME_2 518
#define STATUS_ADDR_OFFCURRENT_TIME_3 519

// MPU related settings - MPU requires ~50 bytes of non-volatile storage
#define CONFIG_ADDR_MPU_SETTINGS 600

unsigned long main_perfbench(unsigned long mintime);

#endif /* GLOBAL_H_ */
